version: '3'

services:
  scraping-service:
    build: ./scraping-service-chrome-extension-analysis
    ports:
      - "4000:4000"
    command: sh -c "docker run -i --init --rm -p 4000:4000 --cap-add=SYS_ADMIN --name puppeteer-chrome puppeteer-chrome-linux  node -e "cat ./service.js""
